Principal\Auth\Entity\Permiso:
  type: entity
  table: permiso
  uniqueConstraints:
    rol_recurso_idx:
      columns: [id_rol, id_recurso]
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    createdAt:
      type: datetime
      column: created_at
    updatedAt:
      type: datetime
      column: updated_at
      nullable: true
  manyToOne:
      rol:
        targetEntity:  Principal\Auth\Entity\Rol
        inversedBy: permisos
        cascade: [persist]
        joinColumn:
          name: id_rol
          referencedColumnName: id
          nullable: false
      recurso:
        targetEntity: Principal\Auth\Entity\Recurso
        inversedBy: permisos
        cascade: [persist]
        joinColumn:
          name: id_recurso
          referencedColumnName: id
          nullable: false